version: '3.8'
services:
  server:
    image: client:0.0.1
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/smart
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  service-db:
    image: postgres:14.7-alpine
    ports:
      - "6542:5432"
    environment:
     - POSTGRES_DB=smart
     - POSTGRES_USER=root
     - POSTGRES_PASSWORD=root
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql